services:
  practica-spring:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://practica_spring_db:3306/practica-spring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2Bdaw20242025%%
    ports:
      - "8080:8080"
    depends_on:
      - practica_spring_db

  practica_spring_db:
    image: mysql:8.0
    container_name: practica_spring_db
    environment:
      MYSQL_ROOT_PASSWORD: 2Bdaw20242025%%
      MYSQL_DATABASE: practica-spring
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: