version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: practica-spring
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./practica-spring
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/practica-spring?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 'root'
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./product-app
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
